apiVersion: v1
kind: ReplicationController
metadata:
  name: haproxy
  namespace: kube-system
  labels:
    k8s-app: haproxy
    version: v1
spec:
  replicas: 2
  selector:
    k8s-app: haproxy
    version: v1
  template:
    metadata:
      labels:
        k8s-app: haproxy
        version: v1
    spec:
      containers:
      - name: haproxy
        image: eu.gcr.io/divine-arcade-95810/haproxy:latest
        ports:
        - containerPort: 80
#    env:
#    - name: MY_POD_NAME
#      valueFrom:
#        fieldRef:
#          fieldPath: metadata.name
#    - name: MY_POD_NAMESPACE
#      valueFrom:
#        fieldRef:
#          fieldPath: metadata.namespace
#    - name: MY_POD_IP
#      valueFrom:
#        fieldRef:
#          fieldPath: status.podIP
