apiVersion: v1
kind: Service
metadata:
  name: haproxyservice
  namespace: kube-system
  labels:
    k8s-app: haproxy
spec:
  loadBalancerIP: 104.155.88.242
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    k8s-app: haproxy
  type: LoadBalancer
